lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal

# Site settings
title: "JJ"
description: "Portal of My Repos"

plugins:
  - jekyll-redirect-from